# Generated by Django 4.2.7 on 2023-11-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnergyDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                (
                    "facility",
                    models.ForeignKey(
                        default=5,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auditApp.facility",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnergyAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_hours", models.CharField(default="N/A", max_length=50)),
                ("audit_result", models.FloatField(blank=True, null=True)),
                # ("no_of_users", models.FloatField(blank=True, null=True)),
                # ("per_capita_consumption", models.FloatField(blank=True, null=True)),
                # ("date", models.DateField(auto_now=True)),
                ("devices", models.ManyToManyField(to="auditApp.energydevice")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auditApp.facility",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
        ),
    ]
