# Generated by Django 4.2.7 on 2023-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyaudit",
            name="meter_reading",
            field=models.FloatField(default=0, null=True),)
        
    ]
