# Generated by Django 4.2.7 on 2023-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditApp", "0002_energyaudit_meter_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyaudit",
            name="devices",
            field=models.ManyToManyField(blank=True, to="auditApp.energydevice"),
        ),
    ]
